### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by elisaifutdinova** [devindg/pybuc#26]
Hello, 

I'm using V0.14.13, py3.8 and import:
```
from pybuc import buc
buc.BayesianUnobservedComponents
```

fails with `TypeError: 'type' object is not subscriptable`. Are any fixes planned please? Thanks!

**Comment by devindg** [comment]
I tested your code in a test environment with Python 3.8. Unfortunately, the error your seeing is because the version of Python you're using is too old. For example: [https://stackoverflow.com/questions/75202610/typeerror-type-object-is-not-subscriptable-python](url).

I just pushed a new version of `pybuc` to PyPi, 0.14.14. The only change I made is to the pyproject.toml file, which now requires Python >= 3.9, < 3.11. Please upgrade your version of Python to 3.9 or 3.10.

Sincere apologies for the inconvenience!
